<a href="https://colab.research.google.com/github/danush564/INTRO-TO-DS/blob/main/Day1_and_19th_Intro_to_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as py

In [ ]:
df = py.DataFrame(
    {"a": [4,5,6],
     "b" : [7,8,9],
     "c" : [10,11,12]},
    index = [1,2,3]
)

In [ ]:
df1 = py.DataFrame(
    [[4,5,7],
     [5,8,11],
     [6,9,12]],
    index=[1,2,3],
    columns=['a','b','c']
)

In [ ]:
print(df)
print(df1)

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12
   a  b   c
1  4  5   7
2  5  8  11
3  6  9  12

##19/02/2024 (Monday)

In [ ]:
data = {
    'Name' : ['John','Sarah','Mike','Emily','David'],
    'Age' : [25,31,29,35,27],
    'Gender' : ['M','F','M','F','M'],
    'Salary' : [50000,70000,60000,80000,55000]
    }
df = py.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Gender  5 non-null      object
 3   Salary  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes



---


Describe Command

---

In [ ]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   29.400000  63000.000000
std     3.847077  12041.594579
min    25.000000  50000.000000
25%    27.000000  55000.000000
50%    29.000000  60000.000000
75%    31.000000  70000.000000
max    35.000000  80000.000000

In [ ]:
df.head()

    Name  Age Gender  Salary
0   John   25      M   50000
1  Sarah   31      F   70000
2   Mike   29      M   60000
3  Emily   35      F   80000
4  David   27      M   55000

In [ ]:
df.tail()

    Name  Age Gender  Salary
0   John   25      M   50000
1  Sarah   31      F   70000
2   Mike   29      M   60000
3  Emily   35      F   80000
4  David   27      M   55000

In [ ]:
sorted = df.sort_values(by='Age',ascending=False)
sorted

    Name  Age Gender  Salary
3  Emily   35      F   80000
1  Sarah   31      F   70000
2   Mike   29      M   60000
4  David   27      M   55000
0   John   25      M   50000

In [ ]:
grouped = df.groupby('Gender').mean()['Salary']
grouped

<ipython-input-16-13d97f18d52c>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped = df.groupby('Gender').mean()['Salary']

Gender
F    75000.0
M    55000.0
Name: Salary, dtype: float64

In [ ]:
counted = df.groupby('Gender').count()
counted

        Name  Age  Salary
Gender
F          2    2       2
M          3    3       3

In [ ]:
data = {
    'Name' : ['John','Sarah','Mike','Emily','David'],
    'Age' : [25,31,None,35,27],
    'Gender' : ['M','F','M','F','M'],
    'Salary' : [50000,None,60000,80000,55000]
    }
df = py.DataFrame(data)
df

    Name   Age Gender   Salary
0   John  25.0      M  50000.0
1  Sarah  31.0      F      NaN
2   Mike   NaN      M  60000.0
3  Emily  35.0      F  80000.0
4  David  27.0      M  55000.0

#Removing NULL Values

subset -> will remove the complete row of the mentioned column
how = all -> is to remove null values if entire column is null
how = any -> is to remove null values if any 1 column value is null

In [ ]:
cleaned_any = df.dropna(how='all')
cleaned_any

    Name   Age Gender   Salary
0   John  25.0      M  50000.0
1  Sarah  31.0      F      NaN
2   Mike   NaN      M  60000.0
3  Emily  35.0      F  80000.0
4  David  27.0      M  55000.0

In [ ]:
cleaned_all = df.dropna(how='any')
print(cleaned_all)

    Name   Age Gender   Salary
0   John  25.0      M  50000.0
3  Emily  35.0      F  80000.0
4  David  27.0      M  55000.0

#Finding Duplicates

In [ ]:
import numpy as np
data = {
    'Name' : ['John','Sarah','John','Emily','David'],
    'Age' : [25,31,25,35,27],
    'Gender' : ['M','F','M','F','M'],
    'Salary' : [50000,70000,50000,80000,55000]
    }
df = py.DataFrame(data)
print(df.duplicated())
print("\nNot Duplicated\n")
print(~df.duplicated())

0    False
1    False
2     True
3    False
4    False
dtype: bool

Not Duplicated

0     True
1     True
2    False
3     True
4     True
dtype: bool

#Filtering

In [ ]:
data = {
    'Name' : ['John','Sarah','Mike','Emily','David'],
    'Age' : [25,31,29,35,27],
    'Gender' : ['M','F','M','F','M'],
    'height' : [1.6,1.78,1.65,1.83,1.7]
    }
df = py.DataFrame(data)
filtered = df[(df['Gender'] == 'F') | (df['Gender'] == 'M') & (df['height']>=1.7)]
filtered

    Name  Age Gender  height
1  Sarah   31      F    1.78
3  Emily   35      F    1.83
4  David   27      M    1.70

#Activity 2

In [ ]:
import pandas as pd
df = pd.read_csv('/content/bank_train.csv')

In [ ]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,76,retired,married,secondary,no,2302.0,no,no,telephone,5,feb,110,1,87,2,failure,no
1,66,retired,divorced,unknown,no,53.0,no,no,cellular,12,jul,562,4,-1,0,unknown,yes
2,51,management,married,tertiary,no,2455.0,yes,no,cellular,21,jul,553,1,-1,0,unknown,yes
3,41,blue-collar,married,secondary,no,356.0,yes,no,cellular,14,may,90,5,-1,0,unknown,no
4,51,technician,married,secondary,no,-1944.0,yes,no,cellular,7,may,623,1,-1,0,unknown,yes

In [ ]:
df.tail()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
4461,33,management,married,tertiary,no,133.0,yes,no,unknown,26,may,308,4,-1,0,unknown,no
4462,39,services,divorced,secondary,no,687.0,yes,no,cellular,9,jul,869,1,-1,0,unknown,yes
4463,40,admin.,single,secondary,no,2040.0,yes,no,cellular,18,may,906,2,350,2,failure,yes
4464,31,technician,single,secondary,no,628.0,yes,no,unknown,12,may,1083,2,-1,0,unknown,no
4465,70,retired,divorced,primary,no,383.0,no,no,cellular,28,apr,50,2,-1,0,unknown,no

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4466 entries, 0 to 4465
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4466 non-null   int64
 1   job        4466 non-null   object
 2   marital    4466 non-null   object
 3   education  4466 non-null   object
 4   default    4466 non-null   object
 5   balance    4465 non-null   float64
 6   housing    4466 non-null   object
 7   loan       4466 non-null   object
 8   contact    4466 non-null   object
 9   day        4466 non-null   int64
 10  month      4466 non-null   object
 11  duration   4466 non-null   int64
 12  campaign   4466 non-null   int64
 13  pdays      4466 non-null   int64
 14  previous   4466 non-null   int64
 15  poutcome   4465 non-null   object
 16  deposit    4466 non-null   object
dtypes: float64(1), int64(6), object(10)
memory usage: 593.3+ KB

In [ ]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,4466.000000,4465.000000,4466.000000,4466.000000,4466.000000,4466.000000,4466.000000
mean,41.100090,1484.334378,15.740484,371.089342,2.484774,52.880878,0.866995
std,11.905566,3253.910473,8.448066,346.904391,2.633638,111.146726,2.381197
min,18.000000,-3058.000000,1.000000,3.000000,1.000000,-1.000000,0.000000
25%,32.000000,107.000000,8.000000,137.000000,1.000000,-1.000000,0.000000
50%,38.000000,539.000000,16.000000,256.000000,2.000000,-1.000000,0.000000
75%,49.000000,1728.000000,22.000000,485.000000,3.000000,64.750000,1.000000
max,93.000000,81204.000000,31.000000,3284.000000,43.000000,828.000000,41.000000

#a.  select the rows where clients with primary education have subscribed to a deposit?


---

In [ ]:
df.loc[(df['education'] == 'primary') & (df['deposit'] == 'yes')]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
29,39,blue-collar,divorced,primary,no,1317.0,yes,no,cellular,20,nov,543,1,170,4,other,yes
39,31,unemployed,single,primary,no,163.0,no,no,cellular,30,jan,707,2,2,1,other,yes
56,49,blue-collar,single,primary,no,566.0,yes,no,cellular,25,jul,979,2,-1,0,unknown,yes
66,53,blue-collar,married,primary,yes,-462.0,no,no,cellular,29,jan,470,1,-1,0,unknown,yes
103,42,blue-collar,single,primary,no,4930.0,no,no,unknown,18,jun,973,1,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4411,55,housemaid,married,primary,no,0.0,yes,no,cellular,17,jul,1303,2,-1,0,unknown,yes
4422,80,retired,married,primary,no,1468.0,no,no,cellular,13,jan,330,3,-1,0,unknown,yes
4451,41,blue-collar,married,primary,no,143.0,yes,yes,unknown,2,jun,659,2,-1,0,unknown,yes
4452,53,blue-collar,married,primary,no,421.0,yes,no,cellular,20,nov,677,1,-1,0,unknown,yes
4458,32,blue-collar,married,primary,no,-454.0,yes,yes,cellular,18,may,801,5,355,2,failure,yes

#b.  select the rows where clients who have not subscribed to a deposit?


---

In [ ]:
df.loc[df['deposit'] == 'no']

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,76,retired,married,secondary,no,2302.0,no,no,telephone,5,feb,110,1,87,2,failure,no
3,41,blue-collar,married,secondary,no,356.0,yes,no,cellular,14,may,90,5,-1,0,unknown,no
6,59,retired,married,secondary,no,136.0,no,no,cellular,6,aug,301,4,-1,0,unknown,no
7,34,blue-collar,married,primary,no,5299.0,yes,no,unknown,26,jun,75,5,-1,0,unknown,no
9,44,blue-collar,married,secondary,no,879.0,yes,no,cellular,3,apr,383,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4457,43,management,married,tertiary,no,1336.0,yes,yes,cellular,27,may,82,2,309,1,failure,no
4460,54,retired,married,secondary,no,522.0,no,yes,cellular,14,jul,81,3,-1,0,unknown,no
4461,33,management,married,tertiary,no,133.0,yes,no,unknown,26,may,308,4,-1,0,unknown,no
4464,31,technician,single,secondary,no,628.0,yes,no,unknown,12,may,1083,2,-1,0,unknown,no
4465,70,retired,divorced,primary,no,383.0,no,no,cellular,28,apr,50,2,-1,0,unknown,no

#c. select the rows where clients who have subscribed to a deposit either have a housing or a personal loan?


---

In [ ]:
df.loc[(df['deposit'] == 'yes') & ((df['housing'] == 'yes') | (df['loan'] == 'yes'))]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
2,51,management,married,tertiary,no,2455.0,yes,no,cellular,21,jul,553,1,-1,0,unknown,yes
4,51,technician,married,secondary,no,-1944.0,yes,no,cellular,7,may,623,1,-1,0,unknown,yes
15,37,management,single,tertiary,no,455.0,yes,no,cellular,13,aug,904,6,-1,0,unknown,yes
17,24,admin.,single,tertiary,no,0.0,yes,no,cellular,27,may,122,2,-1,0,unknown,yes
21,33,admin.,married,tertiary,no,79.0,yes,no,cellular,5,may,389,1,195,4,success,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4454,30,blue-collar,single,secondary,no,155.0,yes,yes,cellular,9,jul,1426,3,-1,0,unknown,yes
4458,32,blue-collar,married,primary,no,-454.0,yes,yes,cellular,18,may,801,5,355,2,failure,yes
4459,37,technician,single,secondary,no,3326.0,yes,no,unknown,21,may,799,1,-1,0,unknown,yes
4462,39,services,divorced,secondary,no,687.0,yes,no,cellular,9,jul,869,1,-1,0,unknown,yes
4463,40,admin.,single,secondary,no,2040.0,yes,no,cellular,18,may,906,2,350,2,failure,yes

#d. select the rows where clients with secondary education who have not subscribed to a deposit?


---

In [ ]:
df.loc[(df['education']== 'secondary') & (df['deposit'] == 'no')]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,76,retired,married,secondary,no,2302.0,no,no,telephone,5,feb,110,1,87,2,failure,no
3,41,blue-collar,married,secondary,no,356.0,yes,no,cellular,14,may,90,5,-1,0,unknown,no
6,59,retired,married,secondary,no,136.0,no,no,cellular,6,aug,301,4,-1,0,unknown,no
9,44,blue-collar,married,secondary,no,879.0,yes,no,cellular,3,apr,383,1,-1,0,unknown,no
10,34,services,married,secondary,no,1637.0,yes,no,cellular,21,nov,107,4,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4446,35,services,married,secondary,no,0.0,yes,no,cellular,24,jul,810,1,-1,0,unknown,no
4453,31,services,married,secondary,no,505.0,no,no,cellular,11,jul,773,3,-1,0,unknown,no
4456,54,blue-collar,married,secondary,no,-102.0,yes,no,cellular,27,aug,164,7,-1,0,unknown,no
4460,54,retired,married,secondary,no,522.0,no,yes,cellular,14,jul,81,3,-1,0,unknown,no
4464,31,technician,single,secondary,no,628.0,yes,no,unknown,12,may,1083,2,-1,0,unknown,no

#e. select the rows where  clients who have subscribed to a term deposit as an outcome of the successful marketing campaign?


---

In [ ]:
df.loc[(df['poutcome'] == 'success') & (df['deposit'] == 'yes')]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
19,76,self-employed,married,unknown,no,4984.0,no,no,telephone,28,apr,403,1,182,1,success,yes
21,33,admin.,married,tertiary,no,79.0,yes,no,cellular,5,may,389,1,195,4,success,yes
45,71,retired,divorced,secondary,no,0.0,no,no,cellular,26,feb,771,1,171,1,success,yes
51,68,retired,married,secondary,no,1146.0,no,no,cellular,13,may,356,1,71,5,success,yes
52,46,management,married,tertiary,no,273.0,yes,no,cellular,18,mar,910,2,184,4,success,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4338,38,admin.,divorced,secondary,no,19.0,yes,no,cellular,5,feb,1130,3,251,2,success,yes
4372,20,student,single,secondary,no,215.0,no,no,cellular,24,feb,175,1,92,6,success,yes
4376,42,technician,married,secondary,no,994.0,yes,no,cellular,12,nov,227,3,93,6,success,yes
4408,29,housemaid,single,tertiary,no,19.0,no,no,cellular,4,may,268,1,88,4,success,yes
4448,27,blue-collar,single,secondary,no,535.0,no,no,cellular,16,aug,265,3,95,4,success,yes

#f. select the rows where unemployed clients who have not subscribed to deposit?


---

In [ ]:
df.loc[(df['job'] == 'unemployed') & (df['deposit'] == 'yes')]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
39,31,unemployed,single,primary,no,163.0,no,no,cellular,30,jan,707,2,2,1,other,yes
105,33,unemployed,single,secondary,no,2066.0,no,yes,cellular,9,sep,305,1,749,2,failure,yes
111,26,unemployed,single,tertiary,no,77.0,no,no,cellular,26,apr,175,1,-1,0,unknown,yes
123,22,unemployed,single,tertiary,no,993.0,no,no,cellular,28,jul,115,3,93,1,other,yes
131,56,unemployed,married,secondary,no,0.0,no,no,telephone,2,feb,492,1,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4015,52,unemployed,married,secondary,no,94.0,no,no,cellular,10,nov,293,3,190,10,failure,yes
4062,59,unemployed,married,secondary,no,957.0,no,no,cellular,8,mar,301,1,89,2,success,yes
4215,33,unemployed,married,secondary,no,1211.0,no,no,cellular,7,aug,456,1,-1,0,unknown,yes
4308,43,unemployed,married,secondary,no,0.0,yes,yes,cellular,23,sep,183,2,184,13,failure,yes
4321,50,unemployed,married,secondary,no,3674.0,yes,no,unknown,30,may,886,3,-1,0,unknown,yes